import { Link } from "react-router-dom";

export default function TermsAndConditions() {
  return (
    <div className="max-w-3xl mx-auto p-6 text-gray-800">
      <h1 className="text-3xl font-bold mb-6 text-center">Terms & Conditions</h1>

      <p className="mb-4 text-sm text-gray-600">
        Last Updated: June 28, 2025
      </p>

      <section className="mb-6 space-y-4">
        <h2 className="text-xl font-semibold">1. Acceptance of Terms</h2>
        <p>
          By using this essay revision platform, you agree to be bound by these Terms and Conditions. If you do not agree with any part of these terms, you must not use this service.
        </p>
      </section>

      <section className="mb-6 space-y-4">
        <h2 className="text-xl font-semibold">2. Description of Service</h2>
        <p>
          Our platform allows users to upload essays and receive AI-generated corrections, improvements, and feedback based on the chosen essay type. This tool is for educational and personal improvement purposes only.
        </p>
      </section>

      <section className="mb-6 space-y-4">
        <h2 className="text-xl font-semibold">3. User Content</h2>
        <p>
          You retain ownership of the essays you upload. However, by using this service, you grant us a non-exclusive, limited license to process, analyze, and improve your content solely for the purpose of providing the revision service.
        </p>
      </section>

      <section className="mb-6 space-y-4">
        <h2 className="text-xl font-semibold">4. AI Limitations</h2>
        <p>
          Our revision suggestions are generated by artificial intelligence. While we strive to provide helpful and accurate feedback, we cannot guarantee correctness or suitability for academic submission. Always review revisions before use.
        </p>
      </section>

      <section className="mb-6 space-y-4">
        <h2 className="text-xl font-semibold">5. Data Privacy</h2>
        <p>
          We respect your privacy. Uploaded files and analysis results are not shared with third parties and are used solely for providing the service unless otherwise stated in our Privacy Policy.
        </p>
      </section>

      <section className="mb-6 space-y-4">
        <h2 className="text-xl font-semibold">6. Intellectual Property</h2>
        <p>
          All branding, interface designs, and proprietary features of this platform are owned by the service provider. You may not copy, modify, or reuse any part of the platform without prior written permission.
        </p>
      </section>

      <section className="mb-6 space-y-4">
        <h2 className="text-xl font-semibold">7. Limitation of Liability</h2>
        <p>
          We are not responsible for any direct, indirect, or consequential loss arising from your use of this platform, including academic penalties, data loss, or service interruption.
        </p>
      </section>

      <section className="mb-6 space-y-4">
        <h2 className="text-xl font-semibold">8. Changes to Terms</h2>
        <p>
          We reserve the right to update these Terms and Conditions at any time. Any changes will be posted on this page with an updated date. Continued use of the service implies your acceptance of the revised terms.
        </p>
      </section>

      <section className="mb-6">
        <p className="text-sm">
          For any questions or concerns about these Terms and Conditions, please contact us at{" "}
          <a href="mailto:support@example.com" className="text-blue-600 underline">
            support@example.com
          </a>.
        </p>
      </section>

      <div className="mt-10 text-center">
        <Link to="/signup" className="text-sm text-blue-600">
          ← Back to Signup
        </Link>
      </div>
    </div>
  );
}
